version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-name: brakeman
  - dependency-name: gds-api-adapters
  - dependency-name: gds-sso
  - dependency-name: govspeak
  - dependency-name: govuk_app_config
  - dependency-name: govuk_personalisation
  - dependency-name: govuk_publishing_components
  - dependency-name: govuk_schemas
  - dependency-name: govuk_sidekiq
  - dependency-name: govuk_test
  - dependency-name: rubocop-govuk
  - dependency-name: plek
  - dependency-name: scss_lint-govuk
  - dependency-name: factory_bot_rails
  - dependency-name: rails
  - dependency-name: rails_translation_manager
  - dependency-name: rspec-rails
  - dependency-name: sass-rails
  - dependency-name: sassc-rails
  ignore:
  - dependency-name: foreman
    versions:
    - "> 0.85.0"
  - dependency-name: sprockets
    versions:
    - "> 3.7.2"
  - dependency-name: rspec-rails
    versions:
    - 5.0.0
  - dependency-name: actionpack
    versions:
    - 6.1.2.1
    - 6.1.3
  - dependency-name: activerecord
    versions:
    - 6.1.2.1
    - 6.1.3
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-name: govuk-frontend
  - dependency-name: jasmine-browser-runner
  - dependency-name: jasmine-core
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
