version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    allow:
      # Internal gems
      - dependency-name: gds-api-adapters
        dependency-type: direct
      - dependency-name: govuk*
        dependency-type: direct
      - dependency-name: plek
        dependency-type: direct
      - dependency-name: rails_translation_manager
        dependency-type: direct
      - dependency-name: rubocop-govuk
        dependency-type: direct
      # Framework gems
      - dependency-name: capybara
        dependency-type: direct
      - dependency-name: percy-caybara
        dependency-type: direct
      - dependency-name: rails
        dependency-type: direct
      - dependency-name: rspec-rails
        dependency-type: direct
      - dependency-name: sassc-rails
        dependency-type: direct
      - dependency-name: sprockets
        dependency-type: direct
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    allow:
      # Internal gems
      - dependency-name: stylelint-config-gds
        dependency-type: direct
      - dependency-name: govuk-frontend
        dependency-type: direct
      # Framework gems
      - dependency-name: jasmine-browser-runner
        dependency-type: direct
      - dependency-name: jasmine-core
        dependency-type: direct
      - dependency-name: stylelint
        dependency-type: direct
      - dependency-name: standardx
        dependency-type: direct
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
