on:
  push:
    branches:
      - main
  pull_request:

jobs:
  visual-regression-test-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # Also runs `bundle install`
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: lts/* # use the latest LTS release
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: npx percy exec -- bundle exec rspec --tag visual_regression
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
